colorscheme reeder

add-highlighter global/ number-lines -hlcursor -relative -min-digits 3
add-highlighter global/ show-matching
add-highlighter global/ show-whitespaces -spc "~" -nbsp "" -lf "" -tab "" -indent "" -only-trailing
add-highlighter global/ show-whitespaces -lf "" -spc ""
add-highlighter global/ wrap -indent

set-option global scrolloff 5,5
set-option global autoreload true

# git
hook global InsertIdle .* %{ git show-diff }
hook global WinCreate .* %{ git show-diff }
hook global BufReload .* %{ git show-diff }

# lsp
eval %sh{kak-lsp}
lsp-enable
lsp-auto-hover-enable

set global lsp_hover_anchor true

set-option global modelinefmt "%opt{lsp_modeline} %opt{modelinefmt}"

map global user l ':enter-user-mode lsp<ret>' -docstring 'LSP mode'

map global goto d <esc>:lsp-definition<ret> -docstring 'LSP definition'
map global goto r <esc>:lsp-references<ret> -docstring 'LSP references'
map global goto y <esc>:lsp-type-definition<ret> -docstring 'LSP type definition'

map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'

map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object t '<a-semicolon>lsp-object Class Interface Module Namespace Struct<ret>' -docstring 'LSP class or module'
map global object d '<a-semicolon>lsp-diagnostic-object error warning<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object error<ret>' -docstring 'LSP errors'
