colorscheme reeder

add-highlighter global/ number-lines -hlcursor -relative -min-digits 3
add-highlighter global/ show-matching
add-highlighter global/ show-whitespaces -spc "~" -nbsp " " -lf "" -tab " " -indent " " -only-trailing
add-highlighter global/ show-whitespaces -lf "" -spc " "
add-highlighter global/ wrap -indent -word

set-option global scrolloff 5,5
set-option global autoreload true
set-option global tabstop 4
set-option global indentwidth 4

set-option global grepcmd 'rg --column --smart-case --sort path'

map global normal <c-t> <c-o>
map global normal '#' :comment-line<ret>

hook global BufOpenFile .* %{ editorconfig-load }
hook global BufNewFile .* %{ editorconfig-load }

# Switch cursor color in insert mode

set-face global InsertCursor default,cyan

hook global ModeChange .*:.*:insert %{
    set-face window PrimaryCursor InsertCursor
    set-face window PrimaryCursorEol InsertCursor
}

hook global ModeChange .*:insert:.* %{ try %{
    unset-face window PrimaryCursor
    unset-face window PrimaryCursorEol
} }

# pickers
declare-user-mode pickers
map global user p ':enter-user-mode pickers<ret>' -docstring 'pickers mode'
map global pickers b ':pickers-buffer<ret>' -docstring 'Open fuzzy buffer picker'
map global pickers i ':pickers-buffer-info<ret>' -docstring 'Show currently open buffers'
map global pickers a ':pickers-buffer-alternate<ret>' -docstring 'Switch to previously opened buffer'
map global pickers f ':pickers-file<ret>' -docstring 'Open fuzzy file picker in git root or current working directory'
map global pickers o ':pickers-file-cbd<ret>' -docstring "Open fuzzy file picker in current buffer's directory"
map global pickers g ':pickers-grep<ret>' -docstring "Open grep picker in git root"
map global pickers <a-g> ':pickers-grep-cbd<ret>' -docstring "Open grep picker in buffer's directory"

map global user <space> ':pickers-file<ret>' -docstring 'Search file'
map global user s ':pickers-grep<ret>' -docstring 'Grep'

hook global WinCreate \*pickers-grep\* %{
  map window normal <ret> ':pickers-grep-open<ret>'
  map window normal <a-ret> "%%s<ret>)" -docstring "Select all matched grep text"
  alias window write pickers-grep-write
  alias window w pickers-grep-write
}
hook global WinCreate \*pickers-file\* %{
  map window normal <ret> ':pickers-file-open<ret>'
}
hook global WinCreate \*pickers-buffer\* %{
  map window normal <ret> ':pickers-buffer-open<ret>'
}

# git
declare-git-mode

# enable flag-lines hl for git diff
hook global WinCreate .* %{
    add-highlighter window/git-diff flag-lines Default git_diff_flags
}
# trigger update diff if inside git dir
hook global BufOpenFile .* %{
    evaluate-commands -draft %sh{
        cd $(dirname "$kak_buffile")
        if [ $(git rev-parse --git-dir 2>/dev/null) ]; then
            for hook in WinCreate BufReload BufWritePost; do
                printf "hook buffer -group git-update-diff %s .* 'git update-diff'\n" "$hook"
            done
            printf "map buffer user g ': enter-user-mode git<ret>' -docstring 'git mode'"
        fi
    }
}

# lsp
try %{
    eval %sh{kak-lsp}
    lsp-enable
    # lsp-auto-hover-enable
    lsp-auto-signature-help-enable
    lsp-inlay-hints-enable global
    lsp-inlay-diagnostics-enable global

    set global lsp_hover_anchor true

    set-option global modelinefmt "%opt{lsp_modeline} %opt{modelinefmt}"

    map global user h ':lsp-hover<ret>' -docstring 'lsp hover'
    map global user l ':enter-user-mode lsp<ret>' -docstring 'LSP mode'

    map global goto d <esc>:lsp-definition<ret> -docstring 'LSP definition'
    map global goto r <esc>:lsp-references<ret> -docstring 'LSP references'
    map global goto y <esc>:lsp-type-definition<ret> -docstring 'LSP type definition'

    map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'

    map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
    map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
    map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
    map global object t '<a-semicolon>lsp-object Class Interface Module Namespace Struct<ret>' -docstring 'LSP class or module'
    map global object d '<a-semicolon>lsp-diagnostic-object error warning<ret>' -docstring 'LSP errors and warnings'
    map global object D '<a-semicolon>lsp-diagnostic-object error<ret>' -docstring 'LSP errors'

    # lsp settings

    remove-hooks global lsp-filetype-python
    hook -group lsp-filetype-python global BufSetOption filetype=python %{
        set-option buffer lsp_servers %{
            [ruff]
            args = ["server", "--quiet"]
            root_globs = ["pyproject.toml", "setup.py", "poetry.lock", ".git", ".hg"]
            settings_section = "_"
            [ruff.settings._.globalSettings]
            organizeImports = true
            fixAll = true

            [basedpyright-langserver]
            root_globs = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json", ".git", ".hg"]
            args = ["--stdio"]
        }
    }
}
