#!/bin/sh
s6-svwait -U ~/.s6/pipewire
pw-cli create-node adapter '{ factory.name=support.null-audio-sink node.name=carla-focusrite media.class=Audio/Source/Virtual object.linger=true audio.position=[FL FR] }'
exec carla-rack "$CARLA_SERVICE_CONFIG"
