#!/bin/sh

if [ -d "$1" ]; then
    files="$1/*.$2"
else
    files="$1"
fi

for i in $files; do
    out="$(echo "$i" | rev | cut -d'.' -f2- | rev).aac"
    ffmpeg -i "$i" -map 0:a -c:a libfdk_aac -b:a 128k "$out"
done
