#!/bin/sh

basedir=/media/data
dir="$(printf 'Anime\nRaws\nApron\nAnime/Seasonals Hell\nLive\nMovies\nShows\nMusic\nBooks\nBooks/artbooks\nBooks/manga\nBooks/LN\nBooks/novel\nImages\nPictures/cosplay\ndata_dumps\nnosync\n' | dmenu -p "addtorrent")"


[ -z "$dir" ] && exit

host=http://korone:9091
rpc_url="$host/transmission/rpc"
basedir=/media/data
session_id=$(curl "$rpc_url" -H "$TRANSMISSION_AUTH" | grep -o 'X-Transmission-Session-Id: [0-9a-zA-Z]*')

if [ -e "$1" ]; then
    metainfo=$(base64 -w0 "$1")
    curl "$rpc_url" -H "$session_id" -H "$TRANSMISSION_AUTH" -H 'Content-type: application/json' -d @- << EOF
{"method": "torrent-add",
 "arguments": {
    "paused": false,
    "download-dir": "$basedir/$dir",
    "metainfo": "$metainfo"
}}
EOF
else
    curl "$rpc_url" -H "$session_id" -H "$TRANSMISSION_AUTH" -H 'Content-type: application/json' -d @- << EOF
{"method": "torrent-add", 
 "arguments": {
    "paused": false, 
    "download-dir": "$basedir/$dir", 
    "filename": "$1"
}}
EOF
fi | grep success && notify-send 'Torrent added' 'Starting a new torrent on korone' || notify-send 'ALED' 'Failed to add torrent'
