#!/bin/sh
BACKLIGHT_BACKEND=${BACKLIGHT_BACKEND:-KERNEL}

# precision of 5% in shown brightness value
PRECISION=5

notify() {
    new_backlight=$1
    backlight_id=$(cat "${XDG_RUNTIME_DIR}/backlight_id")
    [ -z "${backlight_id}" ] && backlight_id=0
    notify-send --replace-id="${backlight_id}" "backlight ${new_backlight}%" -h "int:value:${new_backlight}" -p > "${XDG_RUNTIME_DIR}/backlight_id"
}

kern () {
    for output in /sys/class/backlight/*; do
        if [ "${output}" = "/sys/class/backlight/*" ]; then
            echo "no backlight control on outputs"
            break
        fi

        backlight=$(cat "${output}/actual_brightness")
        max_backlight=$(cat "${output}/max_brightness")
        to_perc=$(expr ${max_backlight} / 100)
        if [ -n "$1" ]; then
            if [ -n "$2" ]; then
                new_backlight=$(expr "${backlight}" "$1" \( "$2" \* ${to_perc} \) )
            else
                new_backlight=$($1 \* ${to_perc})
            fi

            [ "${new_backlight}" -gt "${max_backlight}" ] && new_backlight=${max_backlight}
            [ "${new_backlight}" -lt 0 ] && new_backlight=0
            echo "${new_backlight}" > "${output}/brightness"

            new_perc=$(expr ${new_backlight} / ${to_perc} / ${PRECISION} \* ${PRECISION})
            notify "${new_perc}"
        else
            echo "${perc}%"
        fi
    done
}

xbl () {
    case "$1" in
        +)
            xbacklight -inc "$2"
            ;;
        -)
            xbacklight -dec "$2"
            ;;
        [0-9]*)
            xbacklight -set "$1"
            ;;
        *)
            xbacklight | sed 's/\.[0-9]*/%/'
            ;;
    esac
}

case "$BACKLIGHT_BACKEND" in
    KERNEL)
        kern "$@"
        ;;
    XBACKLIGHT)
        xbl "$@"
        ;;
esac

[ -n "$1" ] && pkill -SIGRTMIN+11 someblocks
