#!/bin/sh
export CC_LD=mold
export PYTHONASYNCDEBUG=1
export PYTHONWARNINGS=default
export CFLAGS="-O2 -pipe -ggdb3 -fsanitize=undefined,address -Wall -Wextra -Wpedantic -Werror -D_FORTIFY_SOURCE=3"
export CXXFLAGS="-O2 -pipe -ggdb3 -fsanitize=undefined,address -Wall -Wextra -Wpedantic -Werror -D_FORTIFY_SOURCE=3"

exec "$@"
