#!/bin/sh
url=https://gin.sadaharu.eu/Gin.txt
bot='Ginpachi-Sensei'

pack=$(curl $url | grep '^#' | dmenu -l 30 | cut -d' ' -f1)
[ -n "$pack" ] && echo "irc.rizon.#news */MSG "$bot" XDCC SEND $pack" > ~/.weechat/weechat_fifo
