#!/usr/bin/env bash

# rbw git-credential helper
# Based on https://github.com/lastpass/lastpass-cli/blob/master/contrib/examples/git-credential-lastpass

# A credential helper for git to retrieve usernames and passwords from rbw.
# For general usage, see https://git-scm.com/docs/gitcredentials.
# Here's a quick version:
# 1. Put this somewhere in your path.
# 2. git config --global credential.helper rbw

[ -z "$GIT_CREDENTIAL_RBW_FOLDER" ] && GIT_CREDENTIAL_RBW_FOLDER="git-credential"

declare -A params

if [ "$1" == "get" ]; then
    read line
    while [ -n "$line" ]; do
        key=${line%%=*}
        value=${line#*=}
        params[$key]=$value
        read line
    done

    [ "${params['protocol']}" != "https" ] && exit

    [ -z "${params["host"]}" ] && exit

    rbw ls > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "Please login to rbw to use git credential helper" > /dev/stderr
        exit
    fi

    userdata="$(rbw get --folder "$GIT_CREDENTIAL_RBW_FOLDER" --raw ${params["host"]})"
    user="$(echo "$userdata" | jq -r '.data.username')"
    pass="$(echo "$userdata" | jq -r '.data.password')"

    if [ "$user" == "null" ] || [ "$pass" = "null" ]; then
        echo "Couldn't find host in rbw DB." > /dev/stderr
        exit
    fi

    echo "username=$user"
    echo "password=$pass"
fi
