#!/bin/sh
worktree="$1"

[ -z "$REPONAME" ] && REPONAME="$(basename "$(realpath "$worktree")" .git)"
[ -z "$GITDIRS" ] && GITDIRS="$HOME/git/.gitdirs"

gitdir="$GITDIRS/$REPONAME"

git init --separate-git-dir "$gitdir" "$worktree"
