#!/bin/sh
url="$1"
name="$(basename "$url" .git)"
worktree="$2"
[ -z "$worktree" ] && worktree="$name"
[ -z "$GITDIRS" ] && GITDIRS="$HOME/git/.gitdirs"
mkdir -p "$GITDIRS"

if [ -d "$GITDIRS/$name.git" ]; then 
    GIT_DIR="$GITDIRS/$name.git"
else
    GIT_DIR="$GITDIRS/$name"
fi

[ -z "$worktree" ] && echo "usage: $0 NAME WORKTREE" && exit 1

GIT_WORK_TREE="$(realpath "$worktree")"

if ! git clone --separate-git-dir "$GIT_DIR" "$url" "$GIT_WORK_TREE"; then
    mkdir -p "$GIT_WORK_TREE"
    echo "gitdir: $GIT_DIR" > "$GIT_WORK_TREE/.git"
    git -C "GIT_WORK_TREE" fetch
    git -C "$GIT_WORK_TREE" checkout "$GIT_WORK_TREE"
fi
