#!/bin/sh
url="$1"
[ -z "$REPONAME" ] && REPONAME="$(basename "$url" .git)"
worktree="$2"
[ -z "$worktree" ] && worktree="$REPONAME"
[ -z "$GITDIRS" ] && GITDIRS="$HOME/git/.gitdirs"
mkdir -p "$GITDIRS"

if [ -d "$GITDIRS/$REPONAME.git" ]; then 
    GIT_DIR="$GITDIRS/$REPONAME.git"
else
    GIT_DIR="$GITDIRS/$REPONAME"
fi

[ -z "$worktree" ] && echo "usage: $0 URL WORKTREE" && exit 1

GIT_WORK_TREE="$(realpath "$worktree")"

if ! git clone --separate-git-dir "$GIT_DIR" "$url" "$GIT_WORK_TREE"; then
    export GIT_DIR
    export GIT_WORK_TREE
    mkdir -p "$GIT_WORK_TREE"
    echo "gitdir: $GIT_DIR" > "$GIT_WORK_TREE/.git"
    git fetch
    git checkout "$GIT_WORK_TREE"
fi
