#!/bin/sh
[ -z "$HIKARI_IPFS_GATEWAY" ] && HIKARI_IPFS_GATEWAY=hikari.butaishoujo.moe

while echo x"$1" | grep '^x-.' > /dev/null; do
    [ "$1" = -o ] && noname=1
    [ "$1" = -c ] && copy=1
    shift
done

[ "$noname" = 1 ] && params= || params="?filename=$(basename "$1")"

hash=$(ipfs add "$1" | awk '{print $2}')

url="https://$HIKARI_IPFS_GATEWAY/ipfs/$hash$params"
echo -n "$url"
[ "$copy" = 1 ] && echo -n "$url" | xclip -selection clipboard
