#!/bin/sh
[ -z "$HIKARI_IPFS_GATEWAY" ] && HIKARI_IPFS_GATEWAY=hikari.butaishoujo.moe

while echo x"$1" | grep '^x-.' > /dev/null; do
    [ "$1" = -o ] && noname=1
    [ "$1" = -c ] && copy=1
    shift
done

filename="$(basename "$1")"
[ "$noname" = 1 ] && params= || params="?filename=$(printf "$filename" | jq -sRr @uri)"

hash=$(ipfs add "$1" | awk '{print $2}')
# pin file on hikari
ipfs --api=/ip4/127.0.0.1/tcp/5002 pin "$hash"

url="https://$HIKARI_IPFS_GATEWAY/ipfs/$hash$params"
echo -n "$url"
[ "$copy" = 1 ] && echo -n "$url" | xclip -selection clipboard
