#!/bin/sh
builddir="${1}"
shift
cmd="${1}"
shift

meson introspect "${builddir}" --targets | jq -r '.[] | .target_sources.[] | select(.sources != null) | .sources.[]' | entr -r meson "${cmd}" -C "${builddir}" "${@}"
