#!/bin/sh
# usage: omixer [+|-] n | omixer mute-input | omixer mute-output

notify() {
    omixer_id=$(cat "${XDG_RUNTIME_DIR}/omixer_id")
    [ -z "${omixer_id}" ] && omixer_id=0
    notify-send --replace-id="${omixer_id}" "$@" -p > "${XDG_RUNTIME_DIR}/omixer_id"
}

notify_input() {
    omixer_id=$(cat "${XDG_RUNTIME_DIR}/omixer_input_id")
    [ -z "${omixer_id}" ] && omixer_id=0
    notify-send --replace-id="${omixer_id}" "$@" -p > "${XDG_RUNTIME_DIR}/omixer_input_id"
}

case ${1} in
    toggle-output)
        wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
        notify "Output $(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
        ;;
    toggle-input)
        wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
        notify_input "Input $(wpctl get-volume @DEFAULT_AUDIO_SOURCE@)"
        ;;
    *)
        wpctl set-volume @DEFAULT_AUDIO_SINK@ ${1} -l 1.0
        notify "Output $(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
esac

