#!/bin/sh
# sakuga - play clips from sakugabooru
# USAGE: sakuga TAGS...
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <https://unlicense.org/>

[ -z "$1" ] && echo "USAGE: $(basename $0) TAGS..." && exit 1

base_url="https://www.sakugabooru.com"
tags=$(echo "$*" | sed 's/ /+/g')
show_url="${base_url}/post/show"

urls=$(curl "${base_url}/post.json?limit=100&tags=${tags}" | jq -r ".[] | \"${show_url}/\(.id)\"")
i=1
nurls=${urls}
while [ -n "${nurls}" ]; do
	if [ $i -gt 1 ]; then
		urls="${urls} ${nurls}"
	fi
	i=$(expr $i + 1)
	nurls=$(curl "${base_url}/post.json?limit=100&page=$i&tags=${tags}" | jq -r ".[] | \"${show_url}/\(.id)\"")
done

mpv --prefetch-playlist=yes --loop-playlist=inf --shuffle ${urls}
