#!/bin/sh
WPDIR="$HOME/Pictures/Wallpapers"

[ -z "$2" ] && TARGET="$HOME/.wallpaper" || TARGET="$2"
SRC="$1"
notify-send "wallpaper" "${SRC}"

cp "${SRC}" "${TARGET}" && rc-service -U swaybg restart
