#!/usr/bin/env bash
set -e

die() {
    echo -e " ${NOCOLOR-\e[1;31m*\e[0m }${*}" >&2
    return 1
}

einfo() {
    echo -e " ${NOCOLOR-\e[1;32m*\e[0m }${*}" >&2
}

ewarn() {
    echo -e " ${NOCOLOR-\e[1;33m*\e[0m }${*}" >&2
}

duration() {
    ffprobe -loglevel quiet -select_streams a -show_entries format=duration "$1" |
        sed -n 's/^duration=\([0-9]*\).*$/\1/p'
}

main() {
    [ -z "$1" ] && die "USAGE: $0 AUDIO1 [AUDIO2]"

    outfile=spectrum.png

    duration=$(duration "$1")
    width=$(( duration * 200 )) || exit 1

    spectrumpicfilter=showspectrumpic=s=400x${width}:mode=separate:color=channel:orientation=horizontal

    if [ -z "$2" ]; then
        ffmpeg -i "$1" -lavfi "${spectrumpicfilter}" "$outfile"
    else
        ffmpeg -i "$1" -i "$2" -filter_complex "[0:a] ${spectrumpicfilter} [p1] ; [1:a] ${spectrumpicfilter} [p2] ; [p1] [p2] hstack" -y "$outfile"
    fi
}

main "$@"
