#!/bin/sh
if command -v dwl > /dev/null; then
  export XDG_CURRENT_DESKTOP=wlroots
  export GDK_BACKEND=wayland
  DWL_STATUS_PIPE="$XDG_RUNTIME_DIR/dwl_status"
  pgrep dwl || exec dbus-run-session -- dwl > ${DWL_STATUS_PIPE}
  s6-svscanctl -t \${S6_SCANDIR}
elif command -v startx > /dev/null; then
  pgrep xinit || exec startx
fi
