#!/bin/sh
# usage: toggle_monitors <on|off>"
[ "$1" = on ] || [ "$1" = off ] || exit 1
if [ "$1" = off ]; then
    for o in $(wlr-randr | awk '/^[^[:space:]]+/ {printf $1 " "}'); do
        wlr-randr --output "${o}" --$1
    done
else
    s6-svc -h $S6_SCANDIR/kanshi
fi
