#!/bin/sh
[ -z "$HOST" ] && echo HOST environment variable is not set > /dev/stderr && exit 1
[ -z "$PORT_OUT" ] && echo PORT_OUT environment variable is not set > /dev/stderr && exit 1
[ -z "$PORT_IN" ] && PORT_IN=$PORT_OUT
[ -z "$ADDR_OUT" ] && ADDR_OUT=127.0.0.1

exec ssh -n "$HOST" -L "$PORT_IN:127.0.0.1:$PORT_OUT" -N -T
