#!/bin/sh

latest=$(curl -s https://www.kernel.org/releases.json | jq -r '.latest_stable.version')
[ -z "$latest" ] && exit

if ! uname -r | grep $latest > /dev/null; then
    echo outdated
    notify-send 'New kernel update' "v$latest available"
fi
