# rotate log files weekly.
weekly
#daily

# keep 4 weeks worth of backlogs.
rotate 4

# create new (empty) log files after rotating old ones.
create

# use date as a suffix of the rotated file.
dateext

# compress rotated log files.
compress

notifempty
nomail
noolddir

~/.local/state/rc/*.log {
    notifempty
    missingok
    # easiest to use since I don’t have to HUP the services
    copy
}

~/.local/state/session.log {
    notifempty
    missingok
    # easiest to use since I don’t have to HUP the services
    copy
}
