# Inserts a blank line between shell prompts
add_newline = false

[username]
format = "[$user]($style)@"
show_always = true

[hostname]
format = "[$hostname]($style) "
ssh_only = false

[cmd_duration]
show_notifications = true
min_time_to_notify = 2_000

[git_branch]
format = "on [$branch]($style) "

[package]
format = "is [$version]($style) "
disabled = true
