#!/bin/bash

die() {
	echo -e " ${NOCOLOR-\e[1;31m*\e[0m }${*}" >&2
	exit 1
}

einfo() {
	echo -e " ${NOCOLOR-\e[1;32m*\e[0m }${*}" >&2
}

ewarn() {
	echo -e " ${NOCOLOR-\e[1;33m*\e[0m }${*}" >&2
}

if command -v nvim > /dev/null 2>&1; then
    einfo "updating nvim"
    BOOTSTRAP_NEOVIM=1 nvim --headless
    nvim --headless "+Lazy! restore" +TSUpdateSync +qa || ewarn "nvim ended with status $?"
    echo # nvim sometimes ends without a newline
fi

if command -v pipx > /dev/null 2>&1; then
    einfo "updating pipx packages"
    pipx upgrade-all || die "pipx update failed"
fi

if command -v uv > /dev/null 2>&1; then
    einfo "updating uv tools"
    uv tool upgrade --all || die "pipx update failed"
fi

if [ -d ~/.mozilla/firefox ]; then
    for i in ~/.mozilla/firefox/*/; do
        einfo "installing Betterfox in $i"
        cp -v ~/.mozilla/Betterfox/user.js "$i"
        cat ~/.mozilla/user_pref.js >> "$i/user.js"
    done
else
    ewarn "not installing Betterfox because firefox config directory wasn't found"
fi
