#!/bin/sh

if command -v nvim > /dev/null 2>&1; then
    echo updating nvim
    BOOTSTRAP_NEOVIM=1 nvim --headless
    nvim --headless "+Lazy! restore" +qa
fi

if command -v pipx > /dev/null 2>&1; then
    echo update hikari
    pipx upgrade hikari
fi

for i in ~/.mozilla/firefox/*/; do
    cp -v ~/.mozilla/Betterfox/user.js "$i"
done

echo update uosc ziggy
command -v go > /dev/null 2>&1 && go build -C "$HOME/.config/mpv/submodules/uosc" -ldflags "-s -w" -o "$HOME/.config/mpv/scripts/uosc/bin/ziggy-linux" "$HOME/.config/mpv/submodules/uosc/src/ziggy"
