#!/bin/bash

die() {
	echo -e " ${NOCOLOR-\e[1;31m*\e[0m }${*}" >&2
	exit 1
}

einfo() {
	echo -e " ${NOCOLOR-\e[1;32m*\e[0m }${*}" >&2
}

ewarn() {
	echo -e " ${NOCOLOR-\e[1;33m*\e[0m }${*}" >&2
}

remote=$(git rev-parse --abbrev-ref --symbolic-full-name '@{u}')

einfo "remote branch is $remote"
git fetch "$(echo "$remote" | sed 's|/.*$||')"

command -v gpg > /dev/null || die "gpg not found"
gpg --import ~/.local/odrling.pub 2> /dev/null

dots verify-commit "$remote" || die "verify-commit failed"
einfo "latest commit has known signature"
git rebase --autostash "$remote" || die "rebase failed"

dots-postupdate
