#!/bin/sh -e
remote=$(git rev-parse --abbrev-ref --symbolic-full-name '@{u}')
git fetch "$(echo "$remote" | sed 's|/.*$||')"

command -v gpg > /dev/null || echo gpg not found
gpg --import ~/.local/odrling.pub 2> /dev/null

dots verify-commit "$remote"
git rebase --autostash "$remote"

dots-postupdate
