#!/usr/bin/env python
import gzip
import json
import os
import pathlib
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import TypedDict
from urllib.error import HTTPError
from urllib.request import Request, urlopen


@dataclass
class KaraberusConfig:
    host: str
    token: str


def get_config():
    config_dir = Path(os.environ["XDG_CONFIG_HOME"])
    mpv_karaberus_conf = config_dir / "mpv" / "script-opts" / "karaberus.conf"

    host = "https://karaberus.japan7.bde.enseeiht.fr"
    token = ""

    with mpv_karaberus_conf.open() as f:
        for line in f:
            if line.startswith("host="):
                host = line[len("host=") :].strip()
            if line.startswith("token="):
                token = line[len("token=") :].strip()

    assert token
    return KaraberusConfig(host=host, token=token)


def get_kid():
    return int(os.environ["ROFI_INFO"])


def get_rofi_retv():
    return int(os.environ["ROFI_RETV"])


class KaraberusObject(TypedDict):
    ID: int


class KaraberusMedia(KaraberusObject):
    name: str


class KaraberusArtist(KaraberusObject):
    Name: str


class KaraberusKara(TypedDict):
    ID: int
    Title: str
    SourceMedia: KaraberusMedia | None
    Artists: list[KaraberusArtist]
    Medias: list[KaraberusMedia]


class KaraberusKaras(TypedDict):
    Karas: list[KaraberusKara]


def xdg_cache_home() -> Path:
    if xdg_cache_home_str := os.environ.get("XDG_CACHE_HOME"):
        return Path(xdg_cache_home_str)
    return Path(os.environ["HOME"]) / ".cache"


def xdg_cache_dir() -> Path:
    return xdg_cache_home() / "rofi-karaberus"


def get_karas() -> KaraberusKaras:
    cache_resp = xdg_cache_dir() / "resp.json.gz"
    cache_etag = xdg_cache_dir() / "etag"

    conf = get_config()

    headers = {"Authorization": f"Bearer {conf.token}", "Accept-Encoding": "gzip"}
    if cache_etag.exists():
        headers["If-None-Match"] = cache_etag.read_text()

    url = f"{conf.host}/api/kara"
    req = Request(url, headers=headers)

    try:
        resp = urlopen(req)
        cache_resp.parent.mkdir(exist_ok=True, parents=True)
        with cache_resp.open("wb") as wf:
            if resp.headers.get("Content-Encoding", "") == "gzip":
                gresp = gzip.open(resp)
            else:
                gresp = resp

            with gzip.open(wf, mode="wb") as gzf:
                while buf := gresp.read():
                    _ = gzf.write(buf)

        resp_etag: str
        if resp_etag := resp.headers.get("ETag"):
            _ = cache_etag.write_text(resp_etag)

    except HTTPError as e:
        if e.status != 304:
            raise

    with cache_resp.open("rb") as f:
        return json.load(gzip.open(f))


def set_prompt():
    print("\0prompt\x1fkaraberus")


def send_kara_entries():
    karas = get_karas()["Karas"]
    for kara in karas:
        parts = [kara["Title"]]

        if kara["SourceMedia"]:
            parts.append(kara["SourceMedia"]["name"])

        artist_names = [a["Name"] for a in kara["Artists"]]
        if artist_names:
            parts.append(", ".join(artist_names))

        media_names = [m["name"] for m in kara["Medias"]]
        if media_names:
            parts.append(", ".join(media_names))

        print(f"{' - '.join(parts)}\0info\x1f{kara['ID']}")


def play_kara():
    kid = get_kid()
    conf = get_config()
    cmd = "umpv", f"{conf.host}/karaoke/browse/{kid}"
    _ = subprocess.Popen(
        cmd, start_new_session=True, stdout=subprocess.PIPE, stdin=subprocess.PIPE
    )


def main():
    retv = get_rofi_retv()
    if retv == 0:
        set_prompt()
        send_kara_entries()
    else:
        play_kara()


if __name__ == "__main__":
    main()
