#!/bin/bash

die() {
	echo -e " ${NOCOLOR-\e[1;31m*\e[0m }${*}" >&2
	exit 1
}

einfo() {
	echo -e " ${NOCOLOR-\e[1;32m*\e[0m }${*}" >&2
}

ewarn() {
	echo -e " ${NOCOLOR-\e[1;33m*\e[0m }${*}" >&2
}


runif() {
    if [ -n "$1" ]; then
        shift
        einfo "$*"
        sh -c "$*" || die "$*: failed"
    fi
    return 0
}

runif "$GIT_HOOK_ISORT" isort . --check
runif "$GIT_HOOK_BLACK" black . --check
runif "$GIT_HOOK_RUFF" ruff .
runif "$GIT_HOOK_PYRIGHT" pyright .
runif "$GIT_HOOK_CLANG_FORMAT" 'fd --glob \*.c | xargs clang-format -Werror -n'
runif "$GIT_HOOK_GOFMT" '[ "$(gofmt -l . | wc -l)" -eq 0 ] || (gofmt -l -d .; exit 1)'
