#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "odrling"
email = "florianbadie@odrling.xyz"

[ui]
default-command = ["log", "-r", "ancestors(reachable(@, mutable())::@, 2) | trunk()", "--stat"]
show-cryptographic-signatures = true

[git]
private-commits = "description('private:*')"

[signing]
behavior = "own"
backend = "gpg"
key = "6F833491FFFEDA4FBA26F0E19F85BCBC5A9FDB2F"

[templates]
log = "builtin_log_comfortable"

[aliases]
s = ["log", "--stat"]
l = ["log"]
la = ["log", "-r", "all()"]
ll = ["log", "--git", "--stat"]
p = ["git", "push"]
push = ["git", "push"]
f = ["git", "fetch"]
fa = ["git", "fetch", "--all-remotes"]
fetch = ["git", "fetch"]
ro = ["rebase", "--onto"]
d = ["describe"]
bm = ["bookmark", "move"]
rebaseall = ["rebase", "-s", "roots(mutable())", "-d", "trunk()"]
ra = ["rebase", "-s", "roots(mutable())", "-d", "trunk()"]
