[bar.default]
auto_hide = false
reserve_space = true
position = "right"
background_opacity = 0.85
start = [ "workspaces" ]
center = [ "clock" ]
end = [
    "clipboard",
    "notifications",
    "network",
    "bluetooth",
    "output_volume",
    "volume",
    "battery",
    "privacy"
]
font_weight = 600
margin_edge = 0
margin_ends = 0
radius = 0
shadow = false

[desktop_widgets]
enabled = true
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000003"
]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 144.0
    box_width = 300.0
    cx = 1722.0
    cy = 996.0
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        bands = 32
        show_when_idle = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 144.0
    box_width = 300.0
    cx = 1722.0
    cy = 840.0
    rotation = -0.0
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = true
        layout = "horizontal"
        shadow = false

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 184.0
    box_width = 300.0
    cx = 1722.0
    cy = 660.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        stat = "cpu_usage"
        stat2 = "cpu_temp"
        shadow = false

[widget.media]
hide_when_no_media = true
title_scroll = "on_hover"

[widget.privacy]
hide_inactive = true

[widget.volume]
device = "input"
show_label = false

[widget.output_volume]
show_label = false

[widget.clock]
capsule = false
font_family = "League Spartan Black"
scale = 1.35
format = "{:%H:%M:%S}"
vertical_format = "{:%H\\n•\\n%M\\n•\\n%S}"

[widget.network]
show_label = false

[widget.battery]
display_mode = "graphic"
scale = 0.80
show_label = false

[widget.brightness]
show_label = false

[hot_corners]
enabled = true

    [hot_corners.top_right]
    action = "command"
    command = "noctalia msg panel-open control-center notifications"


[idle]
behavior_order = [ "screen-off", "lock" ]
pre_action_fade_seconds = 5

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 270.0

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 300.0


[location]
sunrise = "07:00"
sunset = "20:00"

[nightlight]
enabled = true

[shell]
clipboard_enabled = false
polkit_agent = true
screen_time_enabled = true
settings_show_advanced = true
show_location = false

    [shell.panel]
    launcher_placement = "attached"

[theme]
builtin = "Catppuccin"
mode = "light"
source = "builtin"
wallpaper_scheme = "m3-rainbow"

[weather]
enabled = false

[shell.animation]
speed = 2.0

